### ISSUE TITLE
swupd stuck maxing out one core for over 12 hours

### ISSUE THREAD

**Issue by jonjonasson** [clearlinux/swupd-client#1070]
**Describe the bug**
swupd auto-update consumes 100% of one cpu core for more than 12 hours at 3,8 GHz. Auto-updates had been working fine for about 6 months.

`sudo journalctl | grep -i swupd` showed no errors.

`sudo strace -p pgrep swupd` showed these three lines over and over very fast:

```
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=, sa_flags=SA_RESTORER, sa_restorer=0x7fe200ddd1c0}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=, sa_flags=SA_RESTORER, sa_restorer=0x7fe200ddd1c0}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=, sa_flags=SA_RESTORER, sa_restorer=0x7fe200ddd1c0}, NULL, 8) = 0
```

**To Reproduce**
Unable to reproduce. Worked after a reboot.

**Expected behavior**
Finish updating in a reasonable time.

**Environment:**
 - Clear Linux OS Version: 30790
 - Platform: Dell XPS (9360)

**Comment by otaviobp** [comment]
We investigated that bug and I could reproduce it here. The fix was part of PR #1069, so it's closed now and should be available on next swupd release.
Swupd was getting into an infinity loop waiting for curl response when there were some connectivity errors during the download. If you see this problem again try to restart swupd.
And if you see that in a new swupd version (> 3.21.0) please reopen the bug.

Thanks

**Comment by phmccarty** [comment]
@otaviobp Did you intend to link to #1061 instead of #1069?

**Comment by otaviobp** [comment]
Yes, sorry, 1069 is completly unrelated. Bad copy and paste. thanks
