### ISSUE TITLE
Confirmation request

### ISSUE THREAD

**Issue by ilmarn** [clearlinux/swupd-client#1151]
Add confirmation request for bundle-add/bundle-remove by default (are you sure: yes/no) with ability to override from command line (eg. swupd bundle-add -y firefox)

**Comment by castulo** [comment]
Thanks for opening a separate issue for this 😃

**Comment by otaviobp** [comment]
We don't have any interactive command on swupd now so adding that would break scripts that uses swupd and change the standard behavior everyone is used to. But I like the idea on adding a new flag (--confirm) that would ask for confirmation on important commands. And that could be configured on a config file for users that likes that. Then instead of the -y we would have a --no-confirm or something like that.
The idea is similar to ```rm -i```
