### ISSUE TITLE
version info must display both installed and version in current OS release

### ISSUE THREAD

**Issue by ketonik** [clearlinux/swupd-client#1275]
swupdate needs a command to get current installed bundle version and also the bundle version in current OS release and display version what that current OS release is.

Example I have php-basic installed, php version 7.3.x I need to know if 7.4 has been released.

swupd bundle-info php-basic

swupd bundle-info php-basic -V latest
none of these commands shows php-extras bundle version that is installed or what is current.

Maybe `swupd check-update` needs to list installed bundles and version and next to that the version of the bundle in the updated current OS release.

**Comment by lebensterben** [comment]
Since this distro is on rolling release, there should not have discrepancies on the version numbers between the package you have and the package available in current OS release.

Since the way swupd manages packages is not package-based, but bundle-based, and bundles may contain many packages, so showing current versions may be very tedious. It would also be slow to fetch the version numbers of so many packages.

I propose that swupd can show the last updated date of a bundle. Though this may not be accurate enough, it could be very useful.

Say you have a package P and from elsewhere you know it is last updated on date D1. And you know it's contained in bundle B, and swupd tells you B was last updated on D2. Should D2 be earlier than D1, it means the latest version of P is not available yet on Clear Linux.

Well, it's also possible D2 is later than D1, but P is not updated while some other package Q in bundle B was updated. In that case this would not be sufficient to know whether we have the latest version available.

But this problem should eventually be solved when a robust update mechanism is available.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bryteise** [comment]
We'll likely need a service to do the look-up between package and os version. Bundle version isn't really important because the bundle version is known by the os version and as @lebensterben notes the bundle contains more than just a package so figuring out what versions of all packages are in a bundle is likely too much information. To work around this today, grab this file https://download.clearlinux.org/releases/32130/clear/source/package-sources (with the clear linux release you are interested in) and grep for the package to get the package version.

**Comment by ketonik** [comment]
I do see how tricky this can be, I wonder if the server can pull data contained in the OS release notes that show previous package version -> updated version similar printed output to screenshot:

![Screen Shot 2020-01-21 at 03 21 02](https://user-images.githubusercontent.com/49221849/72753968-69730180-3c01-11ea-9286-6813c3d3ff69.png)

The basis of this request is spawned by current unknowns of PHP, I can run php-v to get installed version which for me is 7.3.13 but PHP official current is 7.4.1, now there is potential for big shitstorm if I update the OS with no info as to the newly installed PHP version because in itself php has it's own dependancies outside of Clear Linux installed via Composer. 

Naturally it's my job to identify dependancies but there also the other issue where I need to install newly required Composer packages but these require php 7.4.x and the dependancies cannot be satisfied because the installed  php version is 7.3.x, and so Clear Linux doesn't offer yet a 7.4 version branch.

**Comment by ketonik** [comment]
> https://download.clearlinux.org/releases/32130/clear/source/package-sources (with the clear linux release you are interested in) and grep for the package to get the package version.

Thanks, this is helpful.

**Comment by otaviobp** [comment]
We have an issue suggesting a feature that would cover your use case: #1109 
Can I close this issue in favor of that one?

**Comment by ketonik** [comment]
->otaviobp, Fine with me.

**Comment by otaviobp** [comment]
thanks
