### ISSUE TITLE
3rd_party: Create links to binaries exported by a 3rd party repository on bundle-add

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1277]
On a 3rd party repository some files can be exported according to one whitelist. Exported files are going to be marked on Manifest setting the last flag to x like the example:

```F..x    4163f4a329da5276291ffeee367268dfbefda37e927ff7d51dc230359031f652        32000   /usr/bin/binary```

Swupd should create a link to all binaries set as export on /opt/3rd-party/bin/ on a bundle-add.

**Comment by castulo** [comment]
Update: According to @bryteise we need to create scripts for these binaries, not links. Something similar to this -> https://github.com/clearlinux/clr-user-bundles/blob/master/cublib/postjob.go#L26

**Comment by bryteise** [comment]
Things exported in the binary whitelist (there will eventually multiple types of content supported that is whitelisted in addition to things exported to the 3rd-party PATH that this issue is about) should be added to the 3rd-party PATH unless there is a conflict with another 3rd-party bundle in which case the user should be notified.

Setuid files should be flagged in the whitelist and we should verify that files aren't setuid if they are not marked as such (this is a new feature needed for 3rd-party I think because file attributes are not part of the manifest explicitly currently) during extraction and fail to add the bundle in this case.

**Comment by otaviobp** [comment]
> Setuid files should be flagged in the whitelist and we should verify that files aren't setuid if they are not marked as such (this is a new feature needed for 3rd-party I think because file attributes are not part of the manifest explicitly currently) during extraction and fail to add the bundle in this case.

So we won't support files that are have setuid and that aren't going to be exported? Or we need multiple whitelists?

**Comment by bryteise** [comment]
Bundle-add should regenerate the shared 3rd-party directories (things in PATH and eventually others) as the last part of its operation (this means that even bundles that are not added will need to have their shared wrapper scripts etc regenerated).

**Comment by bryteise** [comment]
> So we won't support files that are have setuid and that aren't going to be exported? Or we need multiple whitelists?

Ah you know I had forgotten a bit of our conversation so I am wrong here a little bit.

The implementation we had talked about before was that the 3rd-party content will be either whitelisted or not whitelisted. Then based on the path of the file the type of white-list will be determined (deciding if something goes in say the shared PATH or the shared desktop folder or whatever things we add in the future).

So my earlier statement was incorrect in that the binary whitelist will just be files that are whitelisted in /bin, /usr/bin and /usr/local/bin for now. Other content can be whitelisted but until we have an action to take for it, will be ignored.

With this implementation though handling setuid content will need to have an additional flag. I think we should probably have any files with setuid, sticky or extended attributes flagged and we can just use the same flag type for all of them since they are rare and can be addressed as the same "type". This flag is just to enable content to pass the above mentioned check that will be done on add (and update) if it has these alternate permissions. I'm open to other suggestions here though.

**Comment by otaviobp** [comment]
So we need 2 independent whitelists. One for files to be exported and other for setuid, stick, etc?

**Comment by bryteise** [comment]
> So we need 2 independent whitelists. One for files to be exported and other for setuid, stick, etc?

The other option is for mixer to not enable adding the content with those bits set but I think that is not very good due to not using content the user intended (and we'd still need to verify no 3rd-party content with those attributes existed since it could be an attacker).

So I prefer 2 different types of whitelist at this point (rather than N different types of whitelist depending on what type of export and what file permissions are needed).

As an aside I do think that this is another point in favor of putting file attributes as part of the file line in the manifest (and swupd uses that to set permissions after extraction) rather than depending on the file attributes to be set on the file and be a black box to swupd-client.

**Comment by bryteise** [comment]
>As an aside I do think that this is another point in favor of putting file attributes as part of the file line in the manifest (and swupd uses that to set permissions after extraction) rather than depending on the file attributes to be set on the file and be a black box to swupd-client.

Basically I see two whitelists as a workaround though to a current short coming. It should only be one whitelist once file permissions aren't implicit.
