### ISSUE TITLE
 3rd_party: Add and Remove links to binaries exported by a 3rd party repository on update

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1279]
Related to #1277 and #1278 
On update whitelisted binaries can be added and removed. Create and remove links accordingly

**Comment by bryteise** [comment]
Due to the possibility of conflicts update gets tricky. By default the base OS and 3rd-party repos should be updated if a user specifies an update to run manually with the default options or with an automatic update (these two manual default and auto update should work the same).

The initial behavior of new files being added to the either whitelist during an update should cause a warning to be printed and that 3rd-party repository to not be updated (the user can work around this by passing a flag to update the specific 3rd-party repository). Note that this condition involves handling new includes as well so any bundle that would be added or updated during an update must pass this check.

In the case of conflicts between shared directory whitelist files due to a default update, because changes to the whitelist must be accepted manually by a user they should be prompted by the conflict. Conflicts to the shared directory are not allowed so only one bundle with the whitelisted file should be every allowed to be installed at the same time (the user must choose which bundle they want for now).
