### ISSUE TITLE
Swupd diagnose --file has some unusual behaviors

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1472]
**Describe the bug**
I found 2 different unusual behavior of swupd diagnose family of commands and I decided to group them together because it looks like the root cause is the same.

1) When trying to diagnose one extra file, sometimes it works. Sometimes it doesn't. I am using --quiet for the examples because it's easier to explain, but the bug is not related to using --quiet.
```
$ touch /usr/bin/a1 /usr/bin/a2 /usr/bin/a3
$ swupd diagnose --extra-files-only --file /usr/bin/ --quiet; echo $?
/usr/bin/a3
/usr/bin/a2
/usr/bin/a1
1
$ swupd diagnose --extra-files-only --file /usr/bin/a1 --quiet; echo $?
0
$ swupd diagnose --extra-files-only --file /usr/bin/a2 --quiet; echo $?
/usr/bin/a2
1
$ swupd diagnose --extra-files-only --file /usr/bin/a3 --quiet; echo $?
0
```
I have no idea why it works only for a2.

2) When using `swupd diagnose --file FILE` swupd is diagnosing all files that starts with FILE and not files that are equal FILE, like the documentation states
```
$ rm /usr/bin/lsusb
$ swupd diagnose --file /usr/bin/ls --quiet; echo $?
/usr/bin/lsusb
1
```
The expected would be to fix /usr/bin/ls binary, but not /usr/bin/lsusb

**Comment by castulo** [comment]
Let me ask you this @otaviobp, what would you expect from the following command?
`swupd diagnose --extra-files-only /my_file`

Diagnosing a tracked file (without using --extra-files-only) makes sense because if the file should be there, and is not, it should be identified, if the file is there, but is corrupt, it also should be identified, and if the file is there, but should no longer be there because it is marked as deleted in the manifest, it also needs to be identified. But if we are using an untracked file, and we are using `--extra-files-only` I would not know what to expect, that scenario doesn't make much sense to me. Currently the code looks for the specified file, and since it is not tracked (doesn't exist in any manifest), and only that file was specified, then it just finishes.

Can you shed some light on what it should be expected in that case?

**Comment by castulo** [comment]
never mind, I just found my answer here: https://github.com/clearlinux/swupd-client/blob/master/test/functional/diagnose/diagnose-path.bats#L118
