### ISSUE TITLE
When using --quiet there's no way on knowing if a file was repaired or not

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1504]
For example here: https://github.com/clearlinux/swupd-client/blob/3bb267a2675d093e8e690477b98771ecff5216d6/test/functional/api/api-repair.bats#L89
There's no error message saying we failed to fix file_3.

**Comment by otaviobp** [comment]
I tried to think in a good way to get this information in the stdout output, but I didn't have any good idea. Not sure if we should print all files that are being repaired or only the ones that are successful.

Printing something like this is not bad, but it becomes confusing when there are files with the ':' character. But maybe is the way to go.
```
file1: fixed
file2: not fixed
my_file:123: not fixed
```

@castulo what do you think?

**Comment by castulo** [comment]
> I tried to think in a good way to get this information in the stdout output, but I didn't have any good idea. Not sure if we should print all files that are being repaired or only the ones that are successful.
> 
> Printing something like this is not bad, but it becomes confusing when there are files with the ':' character. But maybe is the way to go.
> 
> ```
> file1: fixed
> file2: not fixed
> my_file:123: not fixed
> ```
> 
> @castulo what do you think?

I think that is good enough. We can also go with the same separator we are using with the normal non quiet output:
```
file1 -> fixed
file2 -> not fixed
```

The one advantage of using this "arrow" is that cannot be part of a file name because the ">" character is not allowed in names.

Either way I'm good if you think using the ":" is better. I guess is rare enough to see files that have that character in the name, so the confusing scenario should very rarely occur

**Comment by otaviobp** [comment]
> The one advantage of using this "arrow" is that cannot be part of a file name because the ">" character is not allowed in names.

Good point. Go with the arrow then
