### ISSUE TITLE
Handle type changes

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/swupd-client#209]
For the trivial case, empty dir -> symlink the code should work to just remove the dir and create a new link. However, considering the case of a directory that's populated, we need to do better:

If dir is empty: rmdir & create link
If dir is not empty: all files should be marked deleted, delete all marked files first & try to rmdir
If leftover content remains: mv dir -> dir.timestamp, create the new link/file & continue.
https://github.com/clearlinux/swupd-client/pull/168

**Comment by matthewrsj** [comment]
Is this feature already operational? https://github.com/clearlinux/swupd-client/blob/master/src/staging.c#L262 moves a directory out of the way to `/lost+found` for these types of changes. Do we want to do more than that? Remove instead of move to `/lost+found`? Should we just enable type changes in the server? @tmarcu @phmccarty

**Comment by matthewrsj** [comment]
ping, see question above.

**Comment by otaviobp** [comment]
Fixed
