### ISSUE TITLE
verify --install should be made a top-level command

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#250]
the `--install` flag to the `verify` top-level command should be made a top-level command, and decoupled from the `verify` codepath for a couple reasons:
* `--install` is designed to do something completely different (install an OS to a blank partition/directory)
* `--install` *actually* does something completely different in that it doesn't verify the existing files in the target directory, it just assumes it doesn't need to do anything for them. Perhaps it should be verifying those files when it exists, but it currently does not.

When  moved to a top-level command it should probably be named something different to prevent a new user from running
```
swupd install <bundlename>
```
expecting to install a new bundle (like `apt-get install pkgname`) but accidentally installing a whole OS to the current directory (obviously checks would be in place, however)

**Comment by icarus-sparry** [comment]
"os-install" seems a good name .

**Comment by pohly** [comment]
At the moment, "swupd verify --install" looks for the current format under the target path. Because that directory is usually empty for a clean install, -F has to be used explicitly.

I think it would make more sense to read the default format from the usual place (/usr/share/defaults/swupd/format) when doing a "swupd os-install" and not require the -F parameter for that.
