### ISSUE TITLE
Be consistent about where output goes.

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#294]
Progress output should go to stderr so as not to pollute stdout for processes that read swupd output.

EDIT: we should be consistent about what output we send to stderr or stdout throughout the entire project, not just progress output.

**Comment by phmccarty** [comment]
A followup question here is "what should swupd output entail?". Most of its current output *is* progress output, so answering this question at the same time will also be useful.

**Comment by matthewrsj** [comment]
That's a good point, I was mostly thinking about the cases like "swupd bundle-list" where the list should be the only output to go to stdout. This would probably be different for update etc. where the progress and a success message are most of the output.

**Comment by icarus-sparry** [comment]
In general things should go to stdout if it makes sense for the output to be consumed, either by piping it to another program or using it in a command substitution (i.e. version=$(sudo swupd tell_me_the_version shells) as a hypothetical example). Things like progress meters are of no interest, ditto copyright messages (can we get rid of them by default and add a new option to show it?). It would also be good to have a quiet/verbose setting to turn off the noise.

So something like 'verify' can output to stdout the totals and the filenamess which are bad (preferably with some text which makes it easy to identify that this is a bad name so it doesn't get confused with a total if the bad name is "total: 12345").

**Comment by matthewrsj** [comment]
I would like to rework the swupd CLI implementation and try to standardize swupd output across commands as much as possible. This would help with standardizing progress output. Perhaps this work would be best to wait until we have a plan-of-action for that.

**Comment by matthewrsj** [comment]
@asifhg that is expected. We print the copyright header for all swupd operations.

**Comment by phmccarty** [comment]
Also note that all of that output from `swupd check-update` goes to stderr, not stdout. So, if you are running the command in a script, you could do:

```
sudo swupd check-update 2> /dev/null
status=$?
case $status in
  0) sudo swupd update ;; # perform update
  1) break ;; # ignore, since no update available
  2) echo "check-update failed" ;; # handle fatal error
esac
```

**Comment by otaviobp** [comment]
I disagree that this issue is low priority.

My first impression using swupd-client was that it was hard to understand what was going on because of the quality of the output messages. I've also heard similar complaints about it. And I'm very annoyed that there's no easy way to get errors messages and output messages redirected to different files.

Suggestions:
 - Review all output messages
 - send all errors to stderr and all other output (including progress, but we need to change the dot system in that case) to stdout
 - return value of the swupd command must be always 0 when the command was successfully run, including `swupd autoupdate` and `swupd check-update`
- Add a --verbose option to output all information we are outputting right now (maybe even more) and print just the minimum when --verbose is not set

**Comment by otaviobp** [comment]
> The return codes for check-update are designed so you can also say

Ok, maybe we could keep different outputs for check-update and autoupdate. I've realized that there're other programs doing something similar

**Comment by icarus-sparry** [comment]
Repeating my previous comment. in a different form.

My view is that things which are expected to be consumed by the person running the program should go to stderr, and things that are potentially consumed by programs go to stdout.

So for example I think progress dots/percentages should go to stderr, but the list of files that "swupd verify" complains about goes to stdout.

This means
 ```
 $ files=$(sudo -E swupd verify)
 $ sudo -E swupd verify --picky | grep -v /usr/bin/mysudo
```
will show progress to the user, and still have meaningful data in files, or we can ignore the extra file in /usr/bin 

New stuff.
1. Yes I hate it printing out version information and copyright stuff, makes me think I am on windows.
1. Yes, I think a --verbose flag makes a lot of sense
1. A --quiet flag also would be good.
1. I am not a fan of programs that look to see if stdout is a tty and change behaviour accordingly (e.g. 'ls'). I am prepared to make an exception for "less", "more" "pg" type programs whose raison d'etre is to introduce pauses in output to the tty.

**Comment by otaviobp** [comment]
My main concern is having an output in swupd that is different from what is standard in Linux tools.

The first time I tried to create a script using swupd it was hard for me to know in advance what to expect from the output. I wouldn't expect, for example, to have some output like "Verifying version" or "Verify successful" printed in stderr.

I don't know if this approach is used by other package managers, but they aren't usually used by linux tools in general. I use Arch Linux and pacman doesn't do that. Do you know if dpkg, dnf or rpm does something like this? Maybe it's just because I haven't worked with a lot of different scripts for system maintenance recently.

>This means
>    $ files=$(sudo -E swupd verify)
>     $ sudo -E swupd verify --picky | grep -v /usr/bin/mysudo

Well, that's one example of usage of verify output. What about:

    $ files=$(sudo -E swupd verify)
    $ num_files=$(sudo -E swupd verify --picky | grep "Inspected .* files" | cut [.......])

or

    $ files=$(sudo -E swupd verify)
    $ sudo -E swupd verify --fix 2> error_log_file #I would expected to have just errors on that file

I prefer to have a flag that modifies the output then assuming how the user will use the output. Maybe just adding --quiet and --verbose would help with that. Not sure.

>1. Yes I hate it printing out version information and copyright stuff, makes me think I am on windows.

Current version is not printing anything like that anymore.
> 2 and 3

+1

> 4. I am not a fan of programs that look to see if stdout is a tty and change behaviour accordingly (e.g. 'ls'). I am prepared to make an exception for "less", "more" "pg" type programs whose raison d'etre is to introduce pauses in output to the tty.

I am not particularly against it, but I still prefer to have options disabling/enabling the progress. I was looking for some examples and I've seen both solutions being used. (dd, for example outputs progress to stderr, as you suggested).
