### ISSUE TITLE
libarchive reports "Hard-link target '...' does not exist." for some files

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#351]
```
$ sudo -E swupd update
swupd-client software update 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19560 to 19580
Downloading packs...

<snip>

Extracting desktop pack for version 19580
Error: Hard-link target 'delta/19460-19570-30b2525e5ab4e3f9adda856f037ff47b91b0baa918de5970b6af448aa3c67783-45feb79fde363d743dfbe985d7575e95662dfc2b071d65032c1235115a249a06' does not exist.
        ...15%

<snip>

Update was applied.

<snip>

Update successful. System updated from version 19560 to version 19580
35 files were not in a pack
```

**Comment by matthewrsj** [comment]
libarchive error: https://github.com/libarchive/libarchive/blob/master/libarchive/archive_write_disk_posix.c#L1974

offending `extract_to` at https://github.com/clearlinux/swupd-client/blob/master/src/packs.c#L79

**Comment by cmarcelo** [comment]
Inspecting the tar file, we have those two entries (hashes are shortened):

```
delta/19460-19570-30b25...-45feb...
        type: regular file
        content sha256: a395d...
        size: 105
        uid/gid: 80/80
(...)
delta/19460-19570-ac7c9...-0eea6...
        type: hard link
        linkname: delta/19460-19570-30b25...-45feb...
        size: 0
        uid/gid: 80/80
```

The second file is a hardlink referencing to the first file. The extract code will try to create such a hard link but fails and says that the _target_ cannot be found. I'm not sure whether tar is automatically identifying those different files for us or they are hardlinked in the original file system (most likely the latter, we could verify with devops team).

But why doesn't it work? In swupd-client we set the pathname to `statedir/pathname`, but we don't do the same for the hardlink, so it will try to open the hard link target and fail. Also not that if you run swupd from the `statedir` the error doesn't happen because that's the only place where pathname will lead to a right file.

https://github.com/clearlinux/swupd-client/blob/master/src/archives.c#L143

Adding the same prefix `statedir/` to the hardlink will fix the issue.

**Comment by cmarcelo** [comment]
Worth looking later at the actual files and see if they are just the same contents with different permissions or a lucky case where we get the same delta for two different pairs.

**Comment by icarus-sparry** [comment]
Nice piece of detective work.
