### ISSUE TITLE
swupd search should show all results by default

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#391]
swupd search should ~~optionally~~ print all results in the manner it did before #387 (actually, grouped by bundle would still be nice ~~so it can be more easily machine-parse-able~~. We can also add a flag to output in CSV to be more machine-readable.

**Comment by gvancuts** [comment]
What is the exact meaning you want to give to an `--all-results` flag? Is this about showing all search results (instead of limiting the output to 5 per bundle)?

As a very recent user of Clear Linux, I must admit that I have found using `swupd` *very* confusing. I did not know about this truncating of the output before I came across this feature request (while searching for something different). There is no indication of this that I have come across anywhere (nothing on the website, which contains just three `swupd` commands anyway) but more worryingly, there is nothing at all about that neither in the `sudo swupd search --help` output nor the `sudo swupd search <string>` output results.

The other aspect of `swupd search` that confuses me is that it only returns search results for bundles that are already installed, doesn't it? How can I search for things that I want to install but are not yet installed? E.g. I would like to be able to search for `kubeadm` for example by doing `sudo swupd search kubeadm` and that the output tells me which bundle(s) I can find it in. Is that covered by some of these existing feature requests or would that be a new one?

**Comment by matthewrsj** [comment]
> What is the exact meaning you want to give to an --all-results flag? Is this about showing all search results (instead of limiting the output to 5 per bundle)?

Actually, I decided to make search display all results by default, with an optional `--top NUM` flag to show the top `NUM` results per bundle.

> I did not know about this truncating of the output before I came across this feature request (while searching for something different). There is no indication of this that I have come across anywhere (nothing on the website, which contains just three swupd commands anyway) but more worryingly, there is nothing at all about that neither in the sudo swupd search --help output nor the sudo swupd search <string> output results.

Yes, `swupd search` got some (very) recent rapid changes. Sorry about that. We are fixing it up right now. #408 addresses your concern here by displaying all results by default, requiring `--top` to truncate results and additionally displaying a message when the results were actually truncated.

Additionally #399 fixes an issue with the bundle size being reported.

> it only returns search results for bundles that are already installed, doesn't it?

No.

**Comment by gvancuts** [comment]
>> What is the exact meaning you want to give to an --all-results flag? Is this about showing all search results (instead of limiting the output to 5 per bundle)?
> Actually, I decided to make search display all results by default, with an optional --top NUM flag to show the top NUM results per bundle.

I think this will be a big improvement!

>> I did not know about this truncating of the output before I came across this feature request (while searching for something different). There is no indication of this that I have come across anywhere (nothing on the website, which contains just three swupd commands anyway) but more worryingly, there is nothing at all about that neither in the sudo swupd search --help output nor the sudo swupd search output results.
> Yes, swupd search got some (very) recent rapid changes. Sorry about that. We are fixing it up right now. #408 addresses your concern here by displaying all results by default, requiring --top to truncate results and additionally displaying a message when the results were actually truncated.
> Additionally #399 fixes an issue with the bundle size being reported.

Definitely +1!

>> it only returns search results for bundles that are already installed, doesn't it?
> No.

OK, my bad. My experience with the search feature so far has been rather poor. Is there a way we can improve the search results. As an example, I wanted to find out what to install to have Kubernetes on my Clear Linux system so I search for "kubernetes" but it does not return any pointer to the cloud-native-basic bundle which is the only that essentially provides the Kubernetes tools (kubectl, etc...).

Thanks!

**Comment by matthewrsj** [comment]
> I wanted to find out what to install to have Kubernetes on my Clear Linux system so I search for "kubernetes" but it does not return any pointer to the cloud-native-basic bundle which is the only that essentially provides the Kubernetes tools (kubectl, etc...).

Good question. Right now swupd (client side) only knows about files and bundles. It has no concept of packages (i.e. kubernetes). So to find what bundle installs a certain package you need to search for a file from that package. A good search for the kubernetes in this case would be `swupd search -b kubectl`. The `-b` flag tells swupd to look only for binaries.

We have been getting feature requests for more exposure on the package level (or maybe RPM name level) and have ideas of how to implement this, but it will need to be accompanied by changes to server-side content-creation (https://github.com/clearlinux/mixer-tools)

**Comment by matthewrsj** [comment]
Fixed by #408
