### ISSUE TITLE
Implement fullfile fallbacks for bundle-add subcommand

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#447]
The `bundle-add` subcommand currently consumes zero packs, but it would be helpful to consume fullfiles (as a fallback) in case zero packs do not exist.

**Comment by phmccarty** [comment]
The fallbacks could be added for `verify --install` as well. But first, perhaps it would make sense to refactor the code such as `bundle-add` and `verify --install` become synonymous.

**Comment by otaviobp** [comment]
swupd bundle-add executes verify_fix_path when the file is not present on the zero pack or when it has an incorrect hash, so full files are already downloaded. The same isn't true for verify --install.

I noticed that there's a big intersection between update, bundle-add, verify --fix and verify --install. Is it an interesting proposal do refactor them to reuse more code? If so, it's worth to work on #211 before that because those codes use downloads and retries extensively. 

Or is it better to implement the fullfiles download on verify --install for now?

**Comment by matthewrsj** [comment]
@otaviobp I saw some discussion around this on IRC yesterday (sorry, was busy). Were your questions answered or are they still unresolved?

**Comment by otaviobp** [comment]
I was answered. I'm working on that. Thanks

**Comment by matthewrsj** [comment]
Fixed by #465
