### ISSUE TITLE
Implement recursive removal option for bundle-remove

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#455]
If a user runs `swupd bundle-add` for a bundle that requires new bundles as well (pulled in via bundle includes), it would be helpful if they could `swupd bundle-remove` the same bundle, optionally removing the bundles from the includes list.

This would require a *recursive* bundle remove option, since we would not want to recursively remove the bundles by default.

**Comment by bryteise** [comment]
I'd expect we'd want to have bundles removed that were not manually added. Recursive removal eventually removes os-core so I'm not sure if that makes sense to me compared to just removal of leaf bundles that were not opted into directly.

**Comment by phmccarty** [comment]
Comment from @matthewrsj:

> By default we do not want to do this. Swupd (right now) has no idea if a bundle was added directly or as part of an include. If we remove the entire bundle tree (minus os-core) we will likely be removing a ton of content we shouldn't be removing.
>
> Also, bundles can be included by more than one bundle. This should fail in many cases due to another bundle including the bundle to be removed (that the user didn't say to remove). This is very non-trivial to solve with our current architecture.

**Comment by icarus-sparry** [comment]
Other package systems record if a unit was added directly or as a result of a requirement. We could use the files in /usr/share/clear/bundles to record this information. Once we know if something was added explicitly we would prune the bundle tree at that point. As a special case we could just mark os-core as manually added so it would never get removed automatically.

**Comment by castulo** [comment]
This is how this feature will be implemented:
  
If a bundle has dependencies (include/also-add bundles) and is removed using the `--recursive` flag, the bundle and all its dependencies should be removed from the system, with the following two exceptions:
1) if the dependency is also a dependency of another installed bundle, removing it would break the installed bundle
2) if the dependency was previously added by the user directly, because this means the user specifically wanted this bundle installed in the system
