### ISSUE TITLE
How to revert bakc to earlier versions

### ISSUE THREAD

**Issue by m0nik3r** [clearlinux/swupd-client#456]
As far as I can tell swupd doesn't currently support reverting version. Newer versions of clear linux cause system instability for me, and for the time being would like to try to revert to older software versions if possible

**Comment by matthewrsj** [comment]
You can `swupd verify --fix --picky -m <version>` to go back to `version`

**Comment by icarus-sparry** [comment]
Maybe a documentation issue, if a user can't figure it out?

**Comment by matthewrsj** [comment]
We have several times made the decision not to broadcast this feature (other than in listing the flags in the man page) due to wanting to keep users on the latest, most secure, OS version. If there is a bug in the OS content, the OS should fix it.

Additionally, this is not *officially* supported, since fixing backwards over hard-boundary format bumps can break a system; we've seen it happen before. This is not a huge issue currently since it has been almost a year (not sure on timing) since we had a hard-boundary format bump, but it could easily become an issue again in the future.
