### ISSUE TITLE
Implement bundle-info command

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#461]
The files in `/usr/share/clear/bundles` are currently used by swupd-client to track which bundles are installed on the system. However, it may be nice for those files to store bundle metadata as well; then swupd-client could gain the ability to query that metadata, perhaps with a new `bundle-info` command.

The mixer feature for storing additional metadata is tracked at https://github.com/clearlinux/mixer-tools/issues/333.

**Comment by phmccarty** [comment]
Note that it would be nice to query additional information about bundles that are *not* installed as well. So, the metadata may not originate from `/usr/share/clear/bundles/*` entirely.

Another implementation idea: perhaps another meta-bundle could be created (like `os-core-update-index`) that contains the desired metadata for *all* bundle definitions, and `swupd bundle-info` could parse that file instead.

**Comment by matthewrsj** [comment]
A solution was merged and released in https://github.com/clearlinux/mixer-tools/pull/336 to provide bundle info JSON files under `/usr/share/clear/allbundles/<bundle-name>`. A `bundle-info` command and the `search` command should use this.

**Comment by otaviobp** [comment]
Suggestion on bundle-info parameters:

swupd bundle-info bundle-name
 - prints bundle-info header (title, description, maintainer)

swupd bundle-info --includes bundle-name
 - prints all bundles included by this bundle

swupd bundle-info --packages bundle-name
 - prints all packages that composes this bundle

swupd bundle-info --direct-packages bundle-name
 - prints only packages that this bundle adds directly

swupd bundle-info --files bundle-name
 - prints all files installed by this bundle

Reverse search for those commands:

swupd bundle-info --has-include bundle-name
swupd bundle-info --has-package bundle-name
swupd bundle-info --direct-package bundle-name
swupd bundle-info --has-file file_name
swupd bundle-info --has-include bundle-name

Search functionality:
swupd bundle-info --best-match string
 - look for a bundle name matching the string
 - look for direct-package matching that string
 - look for package matching that string
 - look for file matching that string

**Comment by castulo** [comment]
@otaviobp we should probably include the sizes of the bundles there too as search does

**Comment by castulo** [comment]
More details:
- `bundle-info NAME` should show info for the current version of the bundle by default
- It should also show if the bundle is currently installed or not
- It should show if the bundle is experimental or not
- `bundle-info --latest` should show the info for the latest version of the bundle
- `bundle-info -V VER` should show the info for the specified version of the bundle

**Comment by castulo** [comment]
For showing the bundle size we have the following scenarios for `swupd bundle-info BUNDLE`:

- When BUNDLE is already installed in the system:
  - Show the size of the BUNDLE (contentsize)
  - Show how much space the bundle is taking on disk (size of bundle + size of included bundles + size of optional bundles that are installed)

- When BUNDLE is not installed in the system:
  - Show the size of the BUNDLE (contentsize)
  - Show the size the bundle would take on disk (size of bundle + size of included bundles + size of optional bundles)
  - Show the net increase in size (size of bundle on disk - included/optional bundles already installed)

**Comment by castulo** [comment]
Some of the functionality for bundle-info has been implemented in PR #1079, the missing features will be tracked in separate issues as shown next:

> Suggestion on bundle-info parameters:
> 
> swupd bundle-info bundle-name
> 
> * prints bundle-info header (title, description, maintainer)
> 

The bundle Description and maintainer is information that is currently not available to swupd, to implement this mixer will need to make this info available to swupd. Tracked in #1154

> swupd bundle-info --includes bundle-name
> 
> * prints all bundles included by this bundle
> 
Implemented in #1079 

> swupd bundle-info --packages bundle-name
> 
> * prints all packages that composes this bundle
> 
This information is currently not available to swupd, to implement this mixer will need to make this info available to swupd. Tracked in #1154

> swupd bundle-info --direct-packages bundle-name
> 
> * prints only packages that this bundle adds directly
> 
This information is currently not available to swupd, to implement this mixer will need to make this info available to swupd. Tracked in #1154

> swupd bundle-info --files bundle-name
> 
> * prints all files installed by this bundle
> 
Implemented in #1079 

> Reverse search for those commands:
> 
> swupd bundle-info --has-include bundle-name
> swupd bundle-info --has-package bundle-name
> swupd bundle-info --has-direct-package bundle-name
> swupd bundle-info --has-file file-name
> 
This reverse search functionality will be implemented as part of the `swupd bundle-list` command since it makes more sense in that command, and `--has-include` is already implemented there but it is more appropriately called `--has-deps` (includes + also-add). This implementation will be tracked with issue #1156

> Search functionality:
> swupd bundle-info --best-match string
> 
> * look for a bundle name matching the string
> * look for direct-package matching that string
> * look for package matching that string
> * look for file matching that string

Some of this functionality is already covered by other command like `swupd search-file FILE` and `swupd search SEARCH-TERM`, so it may be more appropriate to implement this search functionality as part of one of those commands or as part of a new search command. It doesn't seem to fit in `bundle-info` anymore. This implementation will be tracked in issue #1158.
