### ISSUE TITLE
swupd tries to download a delta pack with an invalid name

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-client#568]
I was testing some updates today under our Yocto system and was performing an update from version 8 to 9. I noticed something strange in the logs and I was wondering if someone can explain it.

```
Preparing to update from 8 to 9
Running script 'Pre-update'
Downloading packs...
Extracting connectivity pack for version 9
Error for /tmp/swupd-mount.yauIz4/swupd-state/pack-core-from-5-to-9.tar download: Response 403 - HTTP response code said error
Extracting os-core pack for version 9
Starting download retry #1 for https://d174e56q8tcm1h.cloudfront.net/builds/orion/dev/9/pack-core-from-5.tar
Error for /tmp/swupd-mount.yauIz4/swupd-state/pack-core-from-5-to-9.tar download: Response 403 - HTTP response code said error
```

Why would it need to try find the core pack for version 5 to 9? Wouldn't it just need 8 to 9?

**Comment by matthewrsj** [comment]
I don't think I've ever seen that before. That's a `permission denied` error. Could it be something wrong with your update web server configuration? Can you curl that pack?

**Comment by aaronovz1** [comment]
Ok so the permission denied error is from CloudFront when you try access something that doesn't exist. I had a look at the files on the server and I don't see any files with that naming structure. The closest I could find was `pack-core-from-0.tar`.

I have SWUPD_GENERATE_OS_CORE_ZERO_PACK set to false in meta-swupd. The blurb for this variable is:
```
# The zero pack for os-core contains all files that normally are always
# installed on a device. It is only needed for installing from
# scratch with "swupd verify --install".
#
# If that is not needed, then disabling that zero pack with
# SWUPD_GENERATE_OS_CORE_ZERO_PACK = "false" can make update data
# considerably smaller, because only changes need to be stored. Builds
# also become faster because compressing the zero pack is a bottleneck
# (see also https://github.com/clearlinux/swupd-server/issues/73).
#
# Zero packs for other bundles are always created, because "swupd
# bundle add/remove" depends on them.
```

There is no `pack-os-core-from-0.tar` so it seems like that matches the blurb above. I enabled generating delta packs for versions 7 and 8 only, when I generated version 9. I'm confused as to why swupd-client thinks it needs `pack-core-from-0.tar`.

**Comment by matthewrsj** [comment]
I would be confused by that as well. Is there a `core` record in your `Manifest.MoM`? On the client system does `/usr/share/clear/bundles/core` exist? 

The only reason I would expect this to happen is if you created your mix with `core` bundle instead of `os-core`.

Are you using mixer or are you still using the deprecated `swupd-server` project? It kind of sounds like it might be an issue with how `swupd-server` is generating update content, perhaps in the MoM for version 9 is there a record like
```
M...    <hash>    9    core
```
and in the MoM for version 8 is there a record like
```
M...    <hash>    0    core
```
In that case swupd-client will attempt to update the `core` bundle from version 0 to version 9, and will attempt to use a delta pack called `pack-core-from-0.tar`. This shouldn't be a hard failure for swupd-client anyways since it can use fullfile fallbacks, and also this would require at least one bug in swupd-server (there are several, but I'm not aware of one like that).

**Comment by aaronovz1** [comment]
* Manifest.MoM for version 9 does have a record for core
* `/usr/share/clear/bundles/core` does exist
* I am still using the deprecated swupd-server project as I haven't had time yet to try get the docker image with mix working with meta-swupd

MoM for version 8:
```
MANIFEST	4
version:	8
previous:	7
filecount:	8
timestamp:	1536769510
contentsize:	0

M...	211a72a01e6cc8057bdcc97d2d6495946bb54c0ad54e2f51246f3e6452dc3335	1	kernelmodules
M...	4dfbf47fa9d8c6bd829526c83674d0ad33b31b578058d4b777ebf3d8c3d4dacd	5	core
M...	71b90cdab5646e3d8be0004083cf768fec257b6c2aa7673bb7dbbc99dc1ae64f	5	debugging
M...	01c5e5ae61acbec30bc3596358d007b20a960d0a52aeb4ff4cec60e61be8363f	5	security
M...	f4a98a957b4140da8a332224c2b64c666d563f7502e826f0d85efe89cb99ef32	5	security-tools
M...	b022c4e9fa052f88aef8cacc4c4cadeea1cdbfa70ead79aac13b3bc6a3d82b0e	8	connectivity
M...	68e08fdc93b63302cc64a3760b018644958435b1eadc833aeb528634bab270ea	8	dss
M...	7791b570b62e796d430aff40ba7e58583d9df6e54bed167ea3a91173bb4acaf9	8	os-core
```

MoM for version 9
```
MANIFEST	4
version:	9
previous:	8
filecount:	8
timestamp:	1536851343
contentsize:	0

M...	211a72a01e6cc8057bdcc97d2d6495946bb54c0ad54e2f51246f3e6452dc3335	1	kernelmodules
M...	01c5e5ae61acbec30bc3596358d007b20a960d0a52aeb4ff4cec60e61be8363f	5	security
M...	f4a98a957b4140da8a332224c2b64c666d563f7502e826f0d85efe89cb99ef32	5	security-tools
M...	8bd55e1257ea55015a52ea049755a27ce5a57d072da47cbb5307c1bc98f20733	9	connectivity
M...	30ab3face84b999f8c5bb95241a1e80099da043f75cee2565706f3f833138e17	9	core
M...	f95d8bf1d49b1d072bdd4dff040363da0c1c19004f34481f195be5e70f3e8200	9	debugging
M...	2a638e80a091b1259e71497d6cc46535b9ca3b25f3c9ff9b7d1c62b69318d344	9	dss
M...	060dadeb850e33d430c91a630dbe0697a616b01126f727c171cce389dc321ac3	9	os-core
```

**Comment by matthewrsj** [comment]
ok you have os-core defined as well as core, so I would expect a pack-core-from-0.tar to be created regardless of your settings for os-core.

Regardless, that's not what your original report was about. Sorry I got sidetracked/confused.

swupd-client will look for pack-core-from-5.tar when updating to 9 because in the `from` manifest the last time core was updated was in version 5 and client is going to version 9. What I don't understand is why swupd would ever be looking for pack-core-from-5-**to-9**.tar since that isn't a valid pack name.

Are you using the latest version of swupd-client? You also definitely need to switch to using mixer at some point soon because swupd-client is no longer guaranteed to work with swupd-server.

**Comment by matthewrsj** [comment]
Swupd determines the file name like so:
1. determines current running version of the OS (say 8)
2. determines version to update to (9)
2. determines versions that installed bundles last changed (in this case `core` changed in version 9)
3. for all bundles that changed between current OS version and version trying to update to (so, we are updating from 8 -> 9, core is currently installed at 5, but changed in 9, so we need to update it), download the pack at the following filename:
    `<version-to-update-to>/pack-<bundlename>-from-<last-changed-ver>.tar`

I have no clue why it would look for the `-to-9` in the filename. If you look at the retry it is suddenly retrying with the URL I would expect. Does it do this every time?

**Comment by aaronovz1** [comment]
It appears to happen every time. I have seen it at least 3 times. I'm trying to figure out using mixer instead but it does seem strange to me the latest swupd-client somehow forms the `-to-9` filename.

**Comment by matthewrsj** [comment]
It should definitely not try to download delta packs with that name scheme, since that is invalid. That name scheme is only supposed to be used in the cache as a pack hint file so the pack isn't re-downloaded. My guess is something is going wrong in how we download packs now that we are using the curl-multi code (this is a relatively new internal feature).

**Comment by matthewrsj** [comment]
@otaviobp can you look at this?

**Comment by otaviobp** [comment]
sure. I'll take a look

**Comment by otaviobp** [comment]
> It should definitely not try to download delta packs with that name scheme, since that is invalid. That name scheme is only supposed to be used in the cache as a pack hint file so the pack isn't re-downloaded. My guess is something is going wrong in how we download packs now that we are using the curl-multi code (this is a relatively new internal feature).

According to the logs, swupd is trying to download 9/pack-core-from-5.tar and save it as pack-core-from-5-to-9.tar. That's expected and I don't see any bug in that. I also couldn't find anywhere in source code where '-to-' is used to create a url to download packs.

If you have generated only delta packs from 8->9, 9/pack-core-from-5.tar wasn't created so this file will not be found. Swupd is suppose to download the pack-core-from-0.tar, as @matthewrsj said, so you need to generate zero packs. 

So, I couldn't find any unexpected behavior in the reported logs. @matthewrsj Is there any other problems besides the '-to-' url?

**Comment by matthewrsj** [comment]
Sorry, didn't realize that CloudFront is returning that permission denied. Swupd will complain if it gets a permission denied since it is expecting a 404 for missing packs. This is expected.
