### ISSUE TITLE
Create a no-dependency swupd binary

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#699]
Currently there's a big list of files that if corrupted will break swupd execution, like libcur, libarchive, openssl so files (and many other libs), some config files like /usr/share/clear/versionstamp, etc.

It would be great if we had a statically linked swupd with minimal dependency on any other file in order to repair a corrupted system.

**Comment by otaviobp** [comment]
But anyway, it makes sense to have swupd working with minimal dependencies. There are other possible usages as using multiple versions of swupd in the same system at the same time. @gtkramer has some use cases for that too.

**Comment by castulo** [comment]
After some research we came to this conclusion.

#### Pros:

- Reduce the number of things that could get corrupted in the system and break swupd
- Have a swupd binary that can be copied to your system to recover if the installed swupd is not working (for example, if an update breaks swupd for you, you can just copy the binary a previous version to use).
- DevOps build swupd multiple times in different clear chroots. If it was static it could be reused.

#### Cons:
- Statically linked Glibc may not work like the dynamic one because code wasn’t meant to be static (i.e. name resolution does not respect /etc/nsswitch.conf)
- We need to monitor for CVEs in libarchive, curl, openssl and other dependencies. Swupd must be rebuilt when we update those libraries
- The number of swupd direct and indirect dependencies we need to have a statically linked version is huge (around 20~30)
- Building a library statically is easy when the project supports autospec, but not when autospec isn’t used (like openssl)
- Some security measures aren’t available (like load address randomization)
- It seems to be considered a bad practice in general trying to have a program statically linked to all its dependencies (https://akkadia.org/drepper/no_static_linking.html).

#### Conclusion:
The pros aren’t that great to justify the effort on working on all cons.
