### ISSUE TITLE
Improve swupd bundle-remove

### ISSUE THREAD

**Issue by clsulliv** [clearlinux/swupd-client#891]
swupd bundle-remove prints an excessively large dependency tree and its difficult to actually remove bundles at times.

For reference, I tried to remove 'c-basic' from a machine that has 586 bundles installed (many devpkgs, desktop bundles, -dev bundles, etc). This resulted in bundle-remove spewing 24830 lines into my terminal. Sorting through those lines, there's actually only ~360 bundles that depend on it.

With high bundle counts it may be wise to not print the entire tree, and instead print a simple dependency list, preferably with leaf nodes printed first, followed by those only depending on the leaf nodes, and so on.

It would also be nice to be able to remove a bundle and anything that depends on it in one command. If I actually wanted to remove c-basic from my system right now, the way I'd do it is 'swupd bundle-remove <those 360 bundles>' in a loop. Its not too pretty but it would work eventually.

**Comment by otaviobp** [comment]
Thank you for the feedback.
From what I understand you are suggesting 2 different improvements in bundle-remove:

 - Get a better output when I'm trying to remove a bundle that are included by other bundles. We could list all bundles that are blocking the removal instead of a full tree.
 - Add a new cmdline flag to swupd-remove to force removal of a bundle and all other bundles that includes it.

Both suggestions make sense to me.

**Comment by ahkok** [comment]
I'm attempting to clean up a system right now and get rid of 200+ bundles, without reinstalling it.

This task is almost impossible right now.
