### ISSUE TITLE
swupd update does not get content from the desired mirror

### ISSUE THREAD

**Issue by kaiseu** [clearlinux/swupd-client#922]
**Describe the bug**
swupd update does not get content from the desired mirror but from the default mirror with timeout. 

swupd info
Installed version: 28910
Version URL:       http://10.xxx.xx.xx/pub/mirrors/clearlinux/update
Content URL:       http://10.xxx.xx.xx/pub/mirrors/clearlinux/update

root@clr-node ~ # swupd update
Update started.
Error: Curl - Communicating with server timed out - 'https://cdn.download.clearlinux.org/update//version/format27/latest'
Waiting 10 seconds before retrying the download
Retry #1 downloading from https://cdn.download.clearlinux.org/update//version/format27/latest

**Environment (please complete the following information):**
 - Clear Linux OS Version: 28910
 - Platform: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz

**Comment by otaviobp** [comment]
Even when a mirror is set swupd checks if the mirror is updated before proceeding, comparing last version from mirror with the default CL update server. In this case, the fix we need is to stop retrying in the case we don't have access to the default server and reduce the timeout.

Thanks for reporting

**Comment by castulo** [comment]
As @otaviobp mentioned, swupd makes sure the mirror is not too far behind the default CL update server before proceeding. If the mirror is found to be stale (version older than CL update server by 500 or more), or the mirror cannot be accessed (curl fails to get files from it), it is then unset automatically so swupd goes back to using the default CL update server. 

When swupd has errors getting files from the mirror/update server, we have a mechanism in place so depending on the type of error we get back from CURL we either retry the download immediately, we retry the download after a timeout, or we just don't retry the download at all.

The error we are getting from CURL in this case is CURLE_OPERATION_TIMEDOUT (28), which falls in the category of the kind of errors we want curl to retry after sleeping for some time, and keep retrying a few times, since this is most likely related to the server being slow or busy. I f the error we had gotten back from curl had been something like not having access to the server then the strategy would be not to retry at all.

So based on that I think swupd is working as expected in this case. The one thing I think it can be improved are the messages we output to the user, so there are no confusions on what is going on. I will submit a PR to address this.
