### ISSUE TITLE
swupd repair --picky -B bundle deletes critical system files

### ISSUE THREAD

**Issue by iuvbio** [clearlinux/swupd-client#981]
**Describe the bug**
As the title says, running `sudo swupd repair --picky -B <bundle>` deletes system files that should clearly not be deleted and definitely do not belong to the bundle specified. I am no longer able to boot the system, however, `/home` is still intact, as well as `/opt`.

**To Reproduce**
I first ran `sudo swupd repair -B vlc` which reported 14 or so files that should not be there, but could not be removed. Since the `picky` option removes files that should not exist, I then ran `sudo swupd repair --picky -B vlc`, which deleted literally the complete system.

**Expected behavior**
I expected the 14 files to be removed that were previously reported to be incorrect.

**Environment (please complete the following information):**
As I am no longer able to boot the system, I can't run `swupd info`, but the system had just auto-updated and therefore was probably on the latest version.
 - Platform: bare metal (installed on usb)

**EDIT**
Apparently, files were removed from `/bin`, `/lib`, `/lib64`, `/sbin`, and `/usr`. `/bin` and `/sbin` contain only vlc related files.

**Comment by castulo** [comment]
is this bug really high priority @otaviobp? This is really not a bug but user error. Although I agree that the command is confusing.

**Comment by castulo** [comment]
This is the proposed solution for the problem:

- Remove the `-B` option from `swupd diagnose` and `swupd repair` since this was really only intended for `swupd os-install`.
- Only allow the use of `-B` with `swupd verify --fix` but we will print a warning saying that running `--picky` after this will remove the other bundles. 

@otaviobp can you confirm this is the expected behavior?

**Comment by otaviobp** [comment]
You can print the warning on verify even if --picky isn't used because we can remove deleted files.
and verify --install should support -B too (but I think this was implicit).

**Comment by castulo** [comment]
> You can print the warning on verify even if --picky isn't used

Yes, the user won't be able to use`-B` or `--picky` together. So the warning would be printed whenever the user uses `-B` regardless of what else is used with.

About this:

> we can remove deleted files

But the files would be removed until a user does a separate `repair --picky` wouldn't they?


> verify --install should support -B too

Sure

**Comment by otaviobp** [comment]
> But the files would be removed until a user does a separate repair --picky wouldn't they?

I though that repair could delete files if the file is set as deleted by the Manifest. Not sure now. If repair isn't deleting files and the problem is just for the --picky case we can just make those flags conflicting. Can you test that?

**Comment by castulo** [comment]
Ok, after clarifying some things with @otaviobp , looks like this should be the proposed solution:

- Remove the `-B` option from `swupd diagnose` and `swupd repair`
- Only allow the use of `-B` with `swupd verify --fix` (and other flags supported with --fix)
- When using `-B` we will print a warning saying that using `-B` removed other bundles from the system

To clarify some wrong statement I made earlier, users will be able to use `-B` with `--fix` and `--picky` together, I had misunderstood the request.

**Comment by iuvbio** [comment]
As a user, this is pretty confusing. Firstly, the [docs](https://github.com/clearlinux/swupd-client/blob/master/docs/swupd.1.rst) state that `verify` has been superseded and `diagnose` should be used instead. `diagnose` doesn't have a `--fix` flag. Additionally, the `--fix` flag for `verify` states that

> This option has been superseded, please consider using "swupd repair" instead.

Which is why I used `repair` in the first place. Now you say that the `-B` option will be removed from `diagnose` and `repair`, leaving us with no option to repair only specific bundles (including removing additional files)?

I'm clearly not into the details (and I really like clear-os great job btw), but from my standpoint it would be sensible to have at most two separate subcommands (one for verify and one for repair, or just one with a `--fix` flag). That command, if used with the `-B` flag, should do exactly what's stated in the docs for `repair`:

> Only verify and repair the (comma separated) list of bundles if installed incorrectly.

If there are additional files, using the `--picky` option should remove only the additional files for the bundle specified as well. That way it would make sense to me at least. Like this, I'm still not sure which command I should have used to only fix the vlc bundle.

**Comment by castulo** [comment]
> As a user, this is pretty confusing. Firstly, the [docs](https://github.com/clearlinux/swupd-client/blob/master/docs/swupd.1.rst) state that `verify` has been superseded and `diagnose` should be used instead. `diagnose` doesn't have a `--fix` flag. Additionally, the `--fix` flag for `verify` states that
> 
> > This option has been superseded, please consider using "swupd repair" instead.
> 
> Which is why I used `repair` in the first place.

`swupd verify` is a command that started growing too big and was performing really 3 different  tasks that should have been separate but they were kept in the same command. Because of this, verify has many flags that are conflicting or confusing. The idea behind splitting `verify` into `diagnose`, `repair` and `os-install`, which are the 3 tasks it was performing, is to make it easier for the user to understand what each of those tasks is, and to make straight forward what flags apply to each one of those tasks. So it is a way to reduce confusion when using flags. That is why `diagnose` doesn't have a --fix flag, because fixing is a different task, and that is what `repair` is used for.



> Now you say that the `-B` option will be removed from `diagnose` and `repair`, leaving us with no option to repair only specific bundles (including removing additional files)?

That is exactly the problem I was describing above about having 3 different tasks being performed by the same `verify` command. The `-B` option was never intended to be used to diagnose/fix only specific bundles, it was designed to be used to install a Clear OS with some specific bundles, that is why we are only making it available in the `os-install` command. Using the `-B` option with `repair` (`verify --fix`), has some side effects that are probably not what the user intents (like wiping out all bundles not selected  in you system). We understand there is a need for users to only diagnose and repair specific bundles, so we will track that in a separate issue. By the way, looks like the info in the docs is misleading, I'll fix that too.



> but from my standpoint it would be sensible to have at most two separate subcommands (one for verify and one for repair, or just one with a `--fix` flag).

You can think of `repair` as a type of `swupd --fix` since it is pretty much what it is.



> That command, if used with the `-B` flag, should do exactly what's stated in the docs for `repair`:
> 
> > Only verify and repair the (comma separated) list of bundles if installed incorrectly.

We will add an option to do this safely with `repair`, but the current `-B` is not the way to do it.



> If there are additional files, using the `--picky` option should remove only the additional files for the bundle specified as well.

We should probably improve the documentation on `--picky` also since it is confusing. This option will remove everything in the `--picky-tree` (/usr by default) that is not listed in any of the manifests from the installed bundles. By using `-B` together with `--picky` you are basically saying to only consider the bundles included with -B which will cause picky to remove all files in the picky tree that were not listed in the manifests from bundles in the -B.

**Comment by iuvbio** [comment]
Thanks for the extensive explanation. 

> The idea behind splitting verify into diagnose, repair and os-install, which are the 3 tasks it was performing, is to make it easier for the user to understand what each of those tasks is, and to make straight forward what flags apply to each one of those tasks.

That makes perfect sense.

> This option will remove everything in the --picky-tree (/usr by default) that is not listed in any of the manifests from the installed bundles. By using -B together with --picky you are basically saying to only consider the bundles included with -B which will cause picky to remove all files in the picky tree that were not listed in the manifests from bundles in the -B.

I'm still wondering why everything was removed also from `bin`, `lib`, etc. if the default picky-tree is `/usr` and I haven't specified a different one. Should then not only the files from `/usr` have been deleted that are not in the bundle's manifest?

> We understand there is a need for users to only diagnose and repair specific bundles, so we will track that in a separate issue.

Looking forward to this.

**Comment by lebensterben** [comment]
>Thanks for the extensive explanation.  ...

@iuvbio I believe they are symlinks to `/use/bin` and `/use/lib64`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
